README.md

Added Example 1 user story

---

SQL/SoftwareEcommerceDB.sql

Added DB Query file to project to create Database for project

Created Initial Database SQL Query File

---

SQL/SoftwareEcommerceDB.sql

Fixed naming for database to match up with connection string in future

Josh db update

---

CPW221-Project-eCom/Models/Customer.cs
CPW221-Project-eCom/Models/CustomerLogin.cs
CPW221-Project-eCom/Models/InvoicedItems.cs
CPW221-Project-eCom/Models/Invoices.cs
CPW221-Project-eCom/Models/Product.cs
CPW221-Project-eCom/Models/ProductCategory.cs

Added initial models for the project. Should not be merged to master until the following occurs:
- Fix usage of datetime and boolean datatypes to translate into usable SQL data in the project
- Add other components to the project to better identify what changes may be needed to the models.

Josh issue#37 40

---

CPW221-Project-eCom/Models/CustomerLogin.cs

Changed CustomerId in the CustomerLogin to CustomerLoginId.

---

CPW221-Project-eCom/Models/CustomerLogin.cs

Added Data Annotation to CustomerLogin class.

---

CPW221-Project-eCom/Models/ProductCategory.cs

Added two close braces to the end of the file.

---

CPW221-Project-eCom/Models/Invoices.cs

Rename boolean to bool on line 49 in Invoices.cs

---

CPW221-Project-eCom/Models/Customer.cs

Fixed lines 77 and 83 to correct the misspelling of the data type bool.

---

CPW221-Project-eCom/Models/Customer.cs

Fixed get or set accessors expected in Customer.cs

---

CPW221-Project-eCom/Models/Customer.cs

Added Data Annotations to customer.cs.

---

CPW221-Project-eCom/Models/CustomerLogin.cs

Updated help on _customer

---

CPW221-Project-eCom/Models/Customer.cs
CPW221-Project-eCom/Models/CustomerLogin.cs

Fixed customer.cs.

---

CPW221-Project-eCom/Models/CustomerLogin.cs

Fixed customerlogin duplicate property

---

CPW221-Project-eCom/Models/Customer.cs
CPW221-Project-eCom/Models/CustomerLogin.cs

Fixed costomer.cs and fixed extra blanks spaces in customerLogin.cs

---

CPW221-Project-eCom/Models/InvoicedItems.cs

Added database annotation to InvoicedItems.

---

CPW221-Project-eCom/appsettings.json

Moved connection string to secrets.

---

CPW221-Project-eCom/appsettings.json

Forgot "SENDGRID_KEY": "Moved to secrets" in the appsettings.json file.

---

CPW221-Project-eCom/CPW221-Project-eCom.csproj

Added forgotten package SendGrid.Extensions.DependencyInjection.

---

CPW221-Project-eCom/CPW221-Project-eCom.csproj
CPW221-Project-eCom/Controllers/HomeController.cs
CPW221-Project-eCom/Models/IEmailProvider.cs
CPW221-Project-eCom/Program.cs

Joe l issue#104 create i email helper

---

CPW221-Project-eCom/Controllers/HomeController.cs

remove testing code from home controller index action.

---

CPW221-Project-eCom/Controllers/HomeController.cs

Removed privacy link from Home controller

---

CPW221-Project-eCom/Controllers/ProductController.cs

Added Create action for the ProductController.

---

CPW221-Project-eCom/Models/Product.cs
CPW221-Project-eCom/Models/ProductCategory.cs

Fixed spelling error in ProductCategory & Added Title to product.

---

CPW221-Project-eCom/Models/Product.cs
CPW221-Project-eCom/Models/SendGridEmailSender.cs
CPW221-Project-eCom/Program.cs

Joe l issue#146 add send grid to microsoft asp.net core identity

---

CPW221-Project-eCom/Controllers/InoviceItemsController.cs
CPW221-Project-eCom/Controllers/InvoicesController.cs

* (x2)Converting null literal or possible null value to non-nullable type.
Fixed the following warnings on InvoicesController:
* (x2)Converting null literal or possible null value to non-nullable type.
Closes #150

Fixed the following warnings on InvoicedItemsController:

---

CPW221-Project-eCom/CPW221-Project-eCom.csproj

Some how MicrosoftEntityCore got uninstalled so I reinstalled it.

---

CPW221-Project-eCom/CPW221-Project-eCom.csproj
CPW221-Project-eCom/Views/Product/Edit.cshtml
CPW221-Project-eCom/Views/Product/Index.cshtml

Joe l issue#133 add edit action and view

---

CPW221-Project-eCom/Controllers/ProductCategoriesController.cs
CPW221-Project-eCom/Views/Product/Delete.cshtml
CPW221-Project-eCom/Views/Product/Details.cshtml
CPW221-Project-eCom/Views/ProductCategories/Create.cshtml
CPW221-Project-eCom/Views/ProductCategories/Delete.cshtml
CPW221-Project-eCom/Views/ProductCategories/Details.cshtml
CPW221-Project-eCom/Views/ProductCategories/Edit.cshtml
CPW221-Project-eCom/Views/ProductCategories/Index.cshtml

Joe l issue#162 add a product category controller

---

CPW221-Project-eCom/Views/Product/Delete.cshtml

Created the basic code for both the action and view for delete.

---

CPW221-Project-eCom/Views/Product/Delete.cshtml
CPW221-Project-eCom/Views/Product/Details.cshtml

Joe l issue#136 add details action and view
